name: Docker Image CI & CD VMware

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Récupération du code
        uses: actions/checkout@v4

      - name: Construction de l'image Docker (Test)
        run: docker build . --file Dockerfile --tag carbon-app:${{ github.sha }}

      - name: Déploiement via SSH sur VMware
        if: github.event_name == 'push'
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            # Vérification du dossier (détecte ai-carbon-app, ai-carbone-app ou carbone-app)
            if [ -d "ai-carbon-app" ]; then
              cd ai-carbon-app
            elif [ -d "ai-carbone-app" ]; then
              cd ai-carbone-app
            elif [ -d "carbone-app" ]; then
              cd carbone-app
            else
              cd carbon-app
            fi

            git pull origin ${{ github.ref_name }}
            sudo docker stop carbon-app || true
            sudo docker rm carbon-app || true
            sudo docker build -t carbon-app:latest .
            sudo docker run -d --name carbon-app -p 3000:3000 --restart always carbon-app:latest
